### ISSUE TITLE
double scrolling bar

### ISSUE THREAD

**Issue by pahud** [DeepSRT/roadmap#7]
## Issue

In certain instances, the sidebar displays redundant scrollbars, significantly degrading the user experience.

<img width="341" alt="Image" src="https://github.com/user-attachments/assets/f1b4b4b3-1f99-4547-97f6-b9246b620e72" />

## Root Cause Analysis

1. The **body element** has a scrollbar by default when content exceeds the viewport height
2. The **.transcript element** also has its own scrollbar due to these CSS properties:
   ```css
   .transcript {
     max-height: calc(100vh - 200px);
     overflow-y: auto;
     /* other styles... */
   }
   ```

This creates two nested scrollable containers, leading to the double scrollbar seen in the UI.

## Proposed Fix
The fix is to implement a flexbox layout where only one container has a scrollbar:

1. Prevent scrolling on the body by setting `overflow: hidden` and using a fixed height:
   ```css
   html, body {
     height: 100vh;
     overflow: hidden;
   }
   ```

2. Make the container use flexbox to fill available space:
   ```css
   .container {
     display: flex;
     flex-direction: column;
     height: 100%;
   }
   ```

3. Allow the transcript to scroll and take remaining space:
   ```css
   .transcript {
     flex: 1;
     overflow-y: auto;
     max-height: none; /* Remove fixed max-height calculation */
   }
   ```

This approach ensures only one scrollbar exists in the UI, improving the user experience.

```mermaid
flowchart TB
    subgraph Current["Current Implementation"]
        subgraph Browser1["Browser Viewport"]
            subgraph Body1["HTML Body with scrollbar"]
                subgraph Container1["Container div"]
                    Header1["Controls/Header"]
                    Video1["Video Info"]
                    Transcript1["Transcript Container with scrollbar"]
                end
            end
            SB1["Body Scrollbar"] -.- Body1
            SB2["Transcript Scrollbar"] -.- Transcript1
        end
    end
    
    Current --> Proposed
    
    subgraph Proposed["Proposed Solution"]
        subgraph Browser2["Browser Viewport"]
            subgraph Body2["HTML Body (overflow: hidden)"]
                subgraph Container2["Container div (flexbox)"]
                    Header2["Controls/Header"]
                    Video2["Video Info"]
                    Transcript2["Transcript Container (flex: 1)"]
                end
            end
            SB3["Single Scrollbar"] -.- Transcript2
        end
    end
```
